# Generated by Django 5.0.4 on 2024-05-01 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='description',
            new_name='details',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='short_description',
            field=models.CharField(default=datetime.datetime(2024, 5, 1, 1, 34, 48, 562511, tzinfo=datetime.timezone.utc), max_length=64),
            preserve_default=False,
        ),
    ]
