# Generated by Django 5.0.4 on 2024-04-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('accessories', 'Accessories'), ('toy', 'Toy'), ('furniture', 'Furniture'), ('others', 'Others')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_picture', models.ImageField(upload_to='static/auctions/item_pictures')),
                ('auction_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pictures', to='auctions.auctionlist')),
            ],
        ),
    ]
