# Generated by Django 5.0.4 on 2024-04-25 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 9, 14, 40, 644949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='item_number',
            field=models.CharField(default=1000, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
