# Generated by Django 5.0.4 on 2024-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlist_end_time_auctionlist_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='item_number',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='ItemPictures',
        ),
    ]
