# Generated by Django 5.0.4 on 2024-04-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auctionlist_id_auctionlist_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='current_price',
        ),
    ]
