# Generated by Django 5.0.4 on 2024-06-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_postlike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
